version: 0.2

phases:
  pre_build:
    commands:
      - echo Build started
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - printf '{"version":"%s","imageUri":"%s.dkr.ecr.%s.amazonaws.com/%s:%s"}' "$PIPELINE_EXECUTION_ID" "$AWS_ACCOUNT_ID" "$AWS_DEFAULT_REGION" "$IMAGE_REPO_NAME" "$PIPELINE_EXECUTION_ID"> .release.json
      - docker build --build-arg ENV=$ENV --build-arg GITHUB_USERNAME=$GITHUB_USERNAME --build-arg GITHUB_PASSWORD=$GITHUB_PASSWORD -t $IMAGE_REPO_NAME:$PIPELINE_EXECUTION_ID .
      - docker tag $IMAGE_REPO_NAME:$PIPELINE_EXECUTION_ID $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$PIPELINE_EXECUTION_ID
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$PIPELINE_EXECUTION_ID
      - printf '[{"name":"serandives","imageUri":"%s.dkr.ecr.%s.amazonaws.com/%s:%s"}]' "$AWS_ACCOUNT_ID" "$AWS_DEFAULT_REGION" "$IMAGE_REPO_NAME" "$PIPELINE_EXECUTION_ID"> .codepipeline.json
  post_build:
    commands:
      - echo Build completed
artifacts:
    files: .codepipeline.json